spring:
  application:
    name: viebook
  datasource:
    url: jdbc:mysql://localhost:3306/viebook_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

server:
  servlet:
    context-path: /api/v1

app:
  jwt:
    secret: U21hcnREaWdpdGFsTGlicmFyeVNlY3JldEtleUZvckhTMjU2QWxnb3JpdGhtMjAyNA
    access-expiration-ms: 1800000
    refresh-expiration-ms: 604800000

cloudinary:
  cloud-name: docidan7t
  api-key: 131775748839957
  api-secret: 94Gm4Ui5GNzEHzkehkYrh3wVFr4
